In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
#from sklearn.svm import SVC
#from sklearn.naive_bayes import MultinomialNB
#from sklearn.neighbors import KNeighborsClassifier


true = pd.read_csv('True.csv')
fake = pd.read_csv('Fake.csv')

true.head()




title  ...                date
0  As U.S. budget fight looms, Republicans flip t...  ...  December 31, 2017 
1  U.S. military to accept transgender recruits o...  ...  December 29, 2017 
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...  December 31, 2017 
3  FBI Russia probe helped by Australian diplomat...  ...  December 30, 2017 
4  Trump wants Postal Service to charge 'much mor...  ...  December 29, 2017 

[5 rows x 4 columns]

In [ ]:
fake.head()

In [12]:
true['target'] = 1
fake['target'] = 0
true.head()

title  ... target
0  As U.S. budget fight looms, Republicans flip t...  ...      1
1  U.S. military to accept transgender recruits o...  ...      1
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...      1
3  FBI Russia probe helped by Australian diplomat...  ...      1
4  Trump wants Postal Service to charge 'much mor...  ...      1

[5 rows x 5 columns]

In [13]:
news = pd.concat([true, fake]).sample(frac=1).reset_index(drop = True)
news.head()

title  ... target
0   WATCH Trump Fans B*tch And Moan About How Har...  ...      0
1  Macron hurls challenge to Europe - reform or d...  ...      1
2  Kasich calls for 'active steps' to strengthen ...  ...      1
3  UPDATE ON MONSTER MOM Who Kicked Little Boy Ou...  ...      0
4  CRIMINAL HILLARY CLINTON BASHES TRUMP: “He has...  ...      0

[5 rows x 5 columns]

In [14]:
news = news.drop(['title','subject', 'date'], axis = 1)
news.head()

text  target
0  Life is hard. We get it. Every one of us has h...       0
1  ATHENS (Reuters) - Europe risks subjugation to...       1
2  WASHINGTON (Reuters) - Presidential candidate ...       1
3  JUSTICE FOR CHILDREN WITHOUT VOICES: We have s...       0
4  This is a pretty ironic statement for someone ...       0

In [15]:
import re
import string

def clean_text(text):
    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text




In [16]:
news['text'] = news['text'].apply(clean_text)
news.head()

text  target
0  life is hard we get it every one of us has had...       0
1  athens reuters europe risks subjugation to chi...       1
2  washington reuters presidential candidate john...       1
3  justice for children without voices we have sp...       0
4  this is a pretty ironic statement for someone ...       0

In [17]:
x = news['text']
y = news['target']


In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 42)

In [19]:
x_train.shape

(31428,)

In [20]:
x_test.shape

(13470,)

In [21]:
v =  TfidfVectorizer()

In [22]:
xv_train = v.fit_transform(x_train)
xv_test = v.transform(x_test)

In [23]:
LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [24]:
pred_lr = LR.predict(xv_test)
LR.score(xv_test, y_test)


0.9848552338530067

In [25]:
print(classification_report(y_test, pred_lr))



              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7026
           1       0.98      0.99      0.98      6444

    accuracy                           0.98     13470
   macro avg       0.98      0.98      0.98     13470
weighted avg       0.98      0.98      0.98     13470



In [26]:
print(confusion_matrix(y_test, pred_lr))

[[6899  127]
 [  77 6367]]


In [27]:
print(accuracy_score(y_test, pred_lr))

0.9848552338530067


In [28]:
DTC = DecisionTreeClassifier()
DTC.fit(xv_train, y_train)

DecisionTreeClassifier()

In [29]:
pred_dt = DTC.predict(xv_test)
DTC.score(xv_test, y_test)

0.996362286562732

In [30]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7026
           1       1.00      1.00      1.00      6444

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470



In [32]:
rfc = RandomForestClassifier()
rfc.fit(xv_train, y_train)

RandomForestClassifier()

In [33]:
pred_rfc = rfc.predict(xv_test)
rfc.score(xv_test, y_test)

0.9874536005939124

In [34]:
print(classification_report(y_test, pred_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7026
           1       0.99      0.99      0.99      6444

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470



In [36]:
print(confusion_matrix(y_test, pred_rfc))

[[6941   85]
 [  84 6360]]


In [37]:
print(accuracy_score(y_test, pred_rfc))

0.9874536005939124


In [38]:
gbc = GradientBoostingClassifier()
gbc.fit(xv_train, y_train)

GradientBoostingClassifier()

In [39]:
pred_gbc = gbc.predict(xv_test)
gbc.score(xv_test, y_test)

0.995916852264291

In [41]:
print(classification_report(y_test, pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7026
           1       0.99      1.00      1.00      6444

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470



In [40]:
print(confusion_matrix(y_test, pred_gbc))

[[6986   40]
 [  15 6429]]


In [42]:
print(accuracy_score(y_test, pred_gbc))

0.995916852264291


In [45]:
def output_label(n):
    return "Not A Fake News" if n == 1 else "Fake News"

def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(clean_text)

    new_x_test = new_def_test["text"]
    new_xv_test = v.transform(new_x_test)
    pred_LR = LR.predict(new_xv_test)
  #  pred_DT = DTC.predict(new_xv_test)
    pred_RFC = rfc.predict(new_xv_test)
    pred_GBC = gbc.predict(new_xv_test)

    print("\n===== PREDICTIONS =====")
    print("Logistic Regression (LR):", output_label(pred_LR[0]))
    print("Gradient Boosting Classifier (GBC):", output_label(pred_GBC[0]))
    print("Random Forest Classifier (RFC):", output_label(pred_RFC[0]))



In [52]:
news = str(input())
manual_testing(news)

"World Health Organization approves new malaria vaccine for use in Africa.

===== PREDICTIONS =====
Logistic Regression (LR): Fake News
Gradient Boosting Classifier (GBC): Fake News
Random Forest Classifier (RFC): Fake News
